//Authentications
export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED";
export const CHECK_EMAIL = "CHECK_EMAIL";
export const CHECK_EMAIL_FAILED = "CHECK_EMAIL_FAILED";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_FAILED = "SIGNIN_USER_FAILED";
export const OTP_AUTHENTICATION = "OTP_AUTHENTICATION";
export const OTP_AUTHENTICATION_FAILED = "OTP_AUTHENTICATION_FAILED";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_FAILED = "GET_USER_PROFILE_FAILED";
export const LOGOUT_USERS = "LOGOUT_USERS";
export const LOGOUT_USERS_FAILED = "LOGOUT_USERS_FAILED";

//General actionTypes
export const UPDATE_IDENTIFICATION = "UPDATE_IDENTIFICATION";
export const UPDATE_IDENTIFICATION_FAILED = "UPDATE_IDENTIFICATION_FAILED";
export const GET_USER_INFOS = "GET_USER_INFOS";
export const GET_USER_INFOS_FAILED = "GET_USER_INFOS_FAILED";

export const LOADING_USER = "LOADING_USER";


//Admin actionTypes
export const GET_ALL_USER_INFOS = "GET_ALL_USER_INFOS";
export const GET_ALL_USER_INFOS_FAILED = "GET_ALL_USER_INFOS_FAILED";
export const ACTIVATE_USER = "ACTIVATE_USER";
export const ACTIVATE_USER_FAILED = "ACTIVATE_USER_FAILED";